# Generated by Django 5.1.4 on 2025-03-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_approved_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Staff', 'Staff'), ('Doctor', 'Doctor')], max_length=20),
        ),
    ]
