# Generated by Django 5.1.4 on 2025-01-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctor_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nmc_no',
            field=models.CharField(max_length=5),
        ),
    ]
