# Generated by Django 5.1.4 on 2025-01-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_doctor_nmc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile/default.jpg', null=True, upload_to='images/profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending'),
        ),
    ]
