# Generated by Django 5.1.4 on 2025-01-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_profile_image_alter_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/profile/'),
        ),
    ]
