# Generated by Django 5.1.4 on 2025-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile/default.jpg', null=True, upload_to='images/profile/'),
        ),
    ]
