# Generated by Django 5.1.4 on 2025-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrator', 'Administrator'), ('Staff', 'Staff'), ('Doctor', 'Doctor')], max_length=20, null=True),
        ),
    ]
