# Generated by Django 5.1.4 on 2025-02-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nmc_no',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
