# Generated by Django 5.1.4 on 2025-02-12 09:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_dental_complaint', models.CharField(blank=True, max_length=500, null=True)),
                ('marked_weight_change', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=13)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('dob', models.DateField(blank=True, default=datetime.date(2025, 2, 12), null=True)),
                ('gender', models.CharField(max_length=6)),
                ('blood_group', models.CharField(max_length=3)),
                ('age', models.CharField(max_length=3)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(max_length=10)),
                ('occupation', models.CharField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Other', 'Other')], default='Single')),
                ('profile_image', models.ImageField(blank=True, default='images/profile/default.jpg', null=True, upload_to='images/profile/')),
            ],
        ),
        migrations.CreateModel(
            name='LiverHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaundice', models.BooleanField(default=False)),
                ('history_of_liver_disease', models.BooleanField(default=False)),
                ('specifics', models.TextField(blank=True, max_length=500, null=True)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_liver', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalizationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalized', models.BooleanField(default=False)),
                ('admission_date', models.DateField(blank=True, default=datetime.date(2025, 2, 12), null=True)),
                ('specifics', models.TextField(blank=True, max_length=500, null=True)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_hospitalization', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='HeartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest_pain', models.BooleanField(default=False)),
                ('hypertention', models.BooleanField(default=False)),
                ('ankle_edema', models.BooleanField(default=False)),
                ('rheumatic_fever', models.BooleanField(default=False)),
                ('rheumatic_fever_age', models.CharField(blank=True, max_length=3, null=True)),
                ('stroke_history', models.BooleanField(default=False)),
                ('stroke_date', models.DateField(blank=True, default=datetime.date(2025, 2, 12), null=True)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_heart', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_extraction', models.BooleanField(default=False)),
                ('date_of_last_extraction', models.DateField(blank=True, null=True, verbose_name=datetime.date(2025, 2, 12))),
                ('untoward_reaction', models.BooleanField(default=False)),
                ('specifics', models.TextField(blank=True, max_length=500, null=True)),
                ('local_anesthesia_use', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_extraction', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='EarHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_loss', models.BooleanField(default=False)),
                ('ringing_of_ears', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_ear', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delayed_healing', models.BooleanField(default=False)),
                ('increased_appetite', models.BooleanField(default=False)),
                ('family_history', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_diabetes', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='BloodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bruise_easy', models.BooleanField(default=False)),
                ('anemia', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_blood', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='ArthritisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joint_pain', models.BooleanField(default=False)),
                ('joint_swelling', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_arthritis', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='AllergiesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeping_pills', models.BooleanField(default=False)),
                ('aspirin', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('penicilin', models.BooleanField(default=False)),
                ('antibiotics', models.BooleanField(default=False)),
                ('sulfa_drugs', models.BooleanField(default=False)),
                ('local_anesthesia', models.BooleanField(default=False)),
                ('others', models.BooleanField(default=False)),
                ('specifics', models.TextField(blank=True, max_length=500, null=True)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_allergies', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='NervousHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headaches', models.BooleanField(default=False)),
                ('convulsions_or_epilepsy', models.BooleanField(default=False)),
                ('numbness_or_tingles', models.BooleanField(default=False)),
                ('dizziness_or_fainting', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_nervous', to='core.medicalhistory')),
            ],
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='core.patient'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=13)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('relation', models.CharField(blank=True, max_length=15, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_emergency', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RadiographyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiography_therapy', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_radiography', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='RespitoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persistant_cough', models.BooleanField(default=False)),
                ('breathing_difficulty', models.BooleanField(default=False)),
                ('shortness_of_breath', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_respiratory', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='ThyroidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspire_easy', models.BooleanField(default=False)),
                ('apprehension', models.BooleanField(default=False)),
                ('palpitation', models.BooleanField(default=False)),
                ('goiter', models.BooleanField(default=False)),
                ('bulging_eyes', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_thyroid', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='UrinaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increased_frequency', models.BooleanField(default=False)),
                ('burning', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_urinary', to='core.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='WomenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy', models.BooleanField(default=False)),
                ('pregnancy_month', models.CharField(blank=True, max_length=2, null=True)),
                ('breast_feed', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_women', to='core.medicalhistory')),
            ],
        ),
    ]
