# Generated by Django 5.1.4 on 2025-02-12 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicalhistory_patient_liverhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionhistory',
            name='date_of_last_extraction',
            field=models.DateField(blank=True, null=True, verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hearthistory',
            name='stroke_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalizationhistory',
            name='admission_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
