# Generated by Django 5.1.4 on 2025-02-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_extractionhistory_date_of_last_extraction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='reg_no',
        ),
    ]
