# Generated by Django 5.1.4 on 2025-03-01 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_payment_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toothrecord',
            name='severity',
        ),
        migrations.AddField(
            model_name='toothrecord',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(max_length=25),
        ),
        migrations.AlterField(
            model_name='toothrecord',
            name='condition',
            field=models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=50, null=True),
        ),
    ]
