# Generated by Django 5.1.4 on 2025-03-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_toothrecord_severity_toothrecord_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
