# Generated by Django 5.1.4 on 2025-02-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='specifics',
            new_name='hospitalization_specifics',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='liver_disease_specifics',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='untoward_reaction_specifics',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='date_of_last_extraction',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='stroke_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
