# Generated by Django 5.1.4 on 2025-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_treatmentdoctor_treatment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentplan',
            old_name='plan',
            new_name='treatment_plan',
        ),
        migrations.AddField(
            model_name='otherpatienthistory',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherpatienthistory',
            name='betel_nuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherpatienthistory',
            name='calculus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherpatienthistory',
            name='halitosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherpatienthistory',
            name='paan_chewing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherpatienthistory',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherpatienthistory',
            name='stain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherpatienthistory',
            name='tobacco_chewing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_treatment_plan', to='core.patient'),
        ),
    ]
