# Generated by Django 5.1.4 on 2025-03-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_plan_treatmentplan_treatment_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.AddField(
            model_name='patient',
            name='reffered_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
