# Generated by Django 5.1.4 on 2025-02-17 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_specifics_medicalhistory_hospitalization_specifics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='date_of_last_extraction',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='hospitalization_specifics',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='hospitalized',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='local_anesthesia_use',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='prev_extraction',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='untoward_reaction',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='untoward_reaction_specifics',
        ),
        migrations.CreateModel(
            name='OtherPatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_extraction', models.BooleanField(default=False)),
                ('date_of_last_extraction', models.DateField(blank=True, null=True)),
                ('untoward_reaction', models.BooleanField(default=False)),
                ('untoward_reaction_specifics', models.TextField(blank=True, max_length=500, null=True)),
                ('local_anesthesia_use', models.BooleanField(default=False)),
                ('hospitalized', models.BooleanField(default=False)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('hospitalization_specifics', models.TextField(blank=True, max_length=500, null=True)),
                ('sleeping_pills', models.BooleanField(default=False)),
                ('aspirin', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('penicilin', models.BooleanField(default=False)),
                ('antibiotics', models.BooleanField(default=False)),
                ('sulfa_drugs', models.BooleanField(default=False)),
                ('local_anesthesia', models.BooleanField(default=False)),
                ('others', models.BooleanField(default=False)),
                ('specifics', models.TextField(blank=True, max_length=500, null=True)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_other_patients', to='core.medicalhistory')),
            ],
        ),
        migrations.DeleteModel(
            name='AllergiesHistory',
        ),
    ]
