# Generated by Django 5.1.4 on 2025-03-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_patient_dob_patient_reffered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentrecord',
            name='type',
            field=models.CharField(blank=True, choices=[('General Checkup', 'General Checkup'), ('Cleaning', 'Cleaning'), ('Fillings', 'Fillings'), ('Extractions', 'Extractions'), ('Prosthetics', 'Prosthetics'), ('Dental Implants', 'Dental Implants'), ('Root Canals', 'Root Canals'), ('Dental Crowns', 'Dental Crowns'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
