# Generated by Django 5.1.4 on 2025-02-18 11:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_medicalhistory_admission_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending')),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DentalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dental_chart', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_appointment', to='core.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='ToothRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_no', models.CharField(max_length=10)),
                ('condition', models.TextField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('dental_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', to='core.dentalchart')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.TimeField(blank=True, max_length=255, null=True)),
                ('x_ray', models.BooleanField(default=False)),
                ('x_ray_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lab', models.BooleanField(default=False)),
                ('lab_sent', models.CharField(blank=True, choices=[('Medi Dent Nepal', 'Medi Dent Nepal'), ('Proficient Dental Lab', 'Proficient Dental Lab'), ('Other', 'Other')], null=True)),
                ('lab_order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lab_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_treatment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_appointment', to='core.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_td', to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_td', to='core.treatment')),
            ],
        ),
    ]
