# Generated by Django 5.1.4 on 2025-03-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_treatmentrecord_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='chief_dental_complaint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
