# Generated by Django 5.1.4 on 2025-02-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transaction_user_appointment_dentalchart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toothrecord',
            name='severity',
            field=models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=50, null=True),
        ),
    ]
