# Generated by Django 5.1.4 on 2025-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_toothrecord_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile/default.jpg', null=True, upload_to='images/patient/'),
        ),
    ]
