# Generated by Django 5.1.4 on 2025-03-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_medicalhistory_chief_dental_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='antibiotics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='aspirin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='betel_nuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='calculus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='date_of_last_extraction',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='halitosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='hospitalization_specifics',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='hospitalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='local_anesthesia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='local_anesthesia_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='paan_chewing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='penicilin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='prev_extraction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='sleeping_pills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='specifics',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='stain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='sulfa_drugs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='tobacco_chewing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='untoward_reaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='untoward_reaction_specifics',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='OtherPatientHistory',
        ),
    ]
