# Generated by Django 5.1.4 on 2025-02-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_patient_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_image',
        ),
    ]
