# Generated by Django 5.1.4 on 2025-03-08 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_type_treatmentrecord_treatment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentdoctor',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
