# Generated by Django 5.1.4 on 2025-03-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentrecord',
            name='lab_order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
