# Generated by Django 5.1.4 on 2025-02-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_appointment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='plan',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
