# Generated by Django 5.1.4 on 2025-02-20 00:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_treatment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='lab_order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
