# Generated by Django 5.1.4 on 2025-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_treatmentrecord_lab_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
