# Generated by Django 5.1.4 on 2025-02-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_treatment_lab_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='total_treatment_cost',
            new_name='treatment_cost',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='lab_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
