# Generated by Django 5.1.4 on 2025-02-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_total_treatment_cost_treatment_treatment_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, max_length=25, null=True),
        ),
    ]
