# Generated by Django 5.1.4 on 2025-02-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='total_amt',
        ),
    ]
