# Generated by Django 5.1.4 on 2025-04-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_transaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentdoctor',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='treatmentdoctor',
            name='percent',
        ),
        migrations.AddField(
            model_name='treatmentdoctor',
            name='work_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
