# Generated by Django 5.1.4 on 2025-04-21 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='treatment_type',
            field=models.CharField(blank=True, choices=[('General Checkup', 'General Checkup'), ('Dental Cleaning', 'Dental Cleaning'), ('Fillings', 'Fillings'), ('Tooth Extraction', 'Tooth Extraction'), ('Root Canal', 'Root Canal'), ('Dental Crowns', 'Dental Crowns'), ('Braces', 'Braces'), ('Invisalign / Aligners', 'Invisalign / Aligners'), ('Dental Implants', 'Dental Implants'), ('Dentures', 'Dentures'), ('Veneers', 'Veneers'), ('Teeth Whitening', 'Teeth Whitening'), ('Periodontal Treatment', 'Periodontal Treatment'), ('Oral Surgery', 'Oral Surgery'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
