# Generated by Django 5.1.4 on 2025-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
